### PR TITLE
Adds an error message to errors. Fixes #16

### LINKED ISSUE #16: Eats useful errors
Upstream of https://github.com/bower/bower/issues/1476

So, these lines: https://github.com/bower/registry-client/blob/master/lib/register.js#L47-L50

Treat any non-201 error as unknown, even useful errors like "Package already registered". I'm puzzled as to why this would be the behavior: presenting these errors to the client, at least in verbose mode, seems like a bare minimum of usability for very common error cases, ones where other clients - like npm, pip, and so on - would give a useful error message, and bower gives `bower EUNKNOWN      Unknown error: 403`, which doesn't give any useful advice.

### PR DESCRIPTION
**Pull request by tmcw**
This could be better if it could distinguish between server errors
and actually unknown errors (known unknowns), but that would require
the server to provide JSON errors.

### CODE REVIEW

**Comment by tmcw** [comment]
Ping: anyone want to review or merge this? The lack of clear error messages in bower is an impediment to usability.

**Comment by patrickkettner** [comment]
This LGTM, do you have anything against the change @sheerun or @satazor?

**Comment by sheerun** [comment]
It's most likely OK

**Comment by patrickkettner** [comment]
I don't see any possible issue, and the utility is high, so i'm biting the bullet and merging. mea culpa if theres a problem.

**Comment by patrickkettner** [comment]
thanks @tmcw!

**Pull request merged**
