### PR TITLE
Bower no proxy

### PR DESCRIPTION
**Pull request by pdxjohnny**
@sheerun because of https://github.com/bower/bower/issues/857 I added in checking to see if the registry should be accessed through a proxy. Using the plugin method it was not possible to do proxy checking for registries, at least as far as I could tell.

### CODE REVIEW

**Comment by sheerun** [comment]
Hey. Could you add more documentation to should-proxy, add the license, and pass no_proxy variable explicitly?

**Comment by sheerun** [comment]
Also add add the tests to should-proxy

**Comment by pdxjohnny** [comment]
Sounds good

**Comment by brunowego** [comment]
:+1:

**Comment by sheerun** [comment]
Oh. And please pin should-proxy to a version. We don't want unexpected changes :)

**Comment by pdxjohnny** [comment]
The config comes from bower-config so I am using this https://github.com/bower/registry-client/blob/master/Client.js#L11 same method of making sure it has a no_proxy property. Almost done

**Comment by pdxjohnny** [comment]
Ok it has documentation for should-proxy, should-proxy has the MIT license, RegistryClient's this._config is being used as the options to should-proxy, and I added a test in test/Client.js to make sure that this._config.no_proxy is indeed being set. Should be good to go @sheerun

**Comment by sheerun** [comment]
Can we just pass this._config.no_proxy explicitly?

**Comment by pdxjohnny** [comment]
I want to leave the second argument to shouldProxy as a object so that in case shouldProxy needs more information in the future the argument list will never get crazy long. Does this work for passing it explicitly
https://github.com/bower/registry-client/pull/22/files#diff-6545ee45f6c9535564ff7b051bd099a7R92

**Comment by sheerun** [comment]
Just one more idea: I see that request.js supports https_proxy, http_proxy and no_proxy variables: https://github.com/request/request/tree/f0c4ec061141051988d1216c24936ad2e7d5c45d#controlling-proxy-behaviour-using-environment-variables

Maybe it would be better idea to override process.env.no_proxy if this._config.no_proxy is set and do not pass proxy configuration to request.js? It would also fix https://github.com/bower/bower/issues/1426

**Comment by pdxjohnny** [comment]
Good call that was much simpler

**Comment by sheerun** [comment]
One last call: as far as I can read request.js source, the process.env.NO_PROXY has precedence over process.env.no_proxy. It means that if someone runs bower in environment with `NO_PROXY` variable set, request.js will use `NO_PROXY` variable instead of what is set in `this._config.no_proxy`. The same goes for HTTPS_PROXY and HTTP_PROXY.

We probably need to either override both process.env.no_proxy and process.env.NO_PROXY or clear process.env.no_proxy and set process.env.NO_PROXY (I think I like better the second option).

Also, maybe it is good idea to restore env variables after API request ends?

btw. Your `should-proxy` package ignores `NO_PROXY` env variable.

**Comment by pdxjohnny** [comment]
I implemented it the way you suggested however restoring the processes.env variables makes it not work. Probably because the requests are run asynchronously. I left the code to restore in case someone wants it latter. Its just commented out

**Comment by sheerun** [comment]
Maybe it's because you need to instantiate Proxy class on each request instead using singleton?

I hink you also need `Object.prototype.hasOwnProperty` checks in restore function, so you don't clear environment variables if this._config variables are not set.

Maybe clearning lower case env variables and setting upper case variables is DRY?

**Comment by pdxjohnny** [comment]
Even if I make a new Proxy instance it is because process.env is shared globally that restoring causes issues. Also process.env doesnt affect the environment when bower exits so I dont think it matters if they are restored because anything happening within bower should respect the proxies that come from bower-config

**Comment by pdxjohnny** [comment]
I think this should actually be done in bower-config or wherever the config is created from so that anything bower does already has env proxy variables set correctly

**Comment by pdxjohnny** [comment]
Ok because of the bower/config#30 which sets the env proxy variables just the removal of https://github.com/bower/registry-client/pull/22/files#diff-6545ee45f6c9535564ff7b051bd099a7L89 makes registry-client respect the proxies

**Comment by pdxjohnny** [comment]
@satazor can these be merged in please

**Comment by pdxjohnny** [comment]
OK I updated bower/config#30

**Pull request closed without merging**
